POST  http://localhost:9000/oauth2/token?client_id=messaging-client&redirect_uri=http://127.0.0.1:3000/authorized&grant_type=authorization_code&code=k01uz59EW3adeKShJ6x8_PXr8KdbrQKJU4758eyIZDU-ouW3ixMn4OOQ7xvPBR3o_WxUU0w_OcanbqAvNpMjAmb05fMG307NjaiRRGTPPOBNTmz_OIGHlnRGh4r2koNf HTTP/1.1
Content-Type: application/json
Authorization: Basic bWVzc2FnaW5nLWNsaWVudDpzZWNyZXQ=

###
GET 
http://localhost:9000/oauth2/authorize?response_type=code&client_id=messaging-client&scope=openid&state=some-state&redirect_uri=http://127.0.0.1:3000/authorized  
HTTP/1.1
Cookie: JSESSIONID=76D78A9BCF2949CA8D5985B7C5339448

###
GET http://localhost:8090/messages/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJraWQiOiJkNGNjMjg0My01MjZkLTQ0OWUtYTcxMy0yNzRkNDZiMjE3NjIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsIm5iZiI6MTY1Mzg3NTIzOSwic2NvcGUiOlsib3BlbmlkIiwibWVzc2FnZS5yZWFkIiwibWVzc2FnZS53cml0ZSJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTY1Mzg3NTUzOSwiaWF0IjoxNjUzODc1MjM5fQ.QrTWNF9KIKtnxVCn1w-4rXPSXUniPEad2WEdoXPDPSESU9b-5sxTtHIEmksMW70bJP-J_NDd-YPDlRgDhEoddtLjADKT4sbJTzqUGELmihAF1TDYjiNqsFV8vx3CN_5npeddbF5UTzwa6moUnpe-Ppll2VgQ2SDORSPsUNdYJ9C67EznE9NEu_2XKi86wW3JREEqzKprkUhG9zapdRU4C6rUW06krnzmpHh47-pjt2Z6KbbuE3q4xyqur0Uvfsyq6fXUME2AftBIRS0Qs-9BDOp-tu__ApszpMfH2LuLk9zsMHvLwQwxkVYiTh9f5uhYURBHvPJ9KuWkW_yhds3K-Q


###
GET http://localhost:8090/users/oidc-principal HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJraWQiOiJkNGNjMjg0My01MjZkLTQ0OWUtYTcxMy0yNzRkNDZiMjE3NjIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoibWVzc2FnaW5nLWNsaWVudCIsImF6cCI6Im1lc3NhZ2luZy1jbGllbnQiLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTY1Mzg3NjU4MywiaWF0IjoxNjUzODc0NzgzfQ.YoZGyqiFNh_DxlUQ5UeWhUUW6pwBVlk_y2Cwyrl5qFzUGz30DW0jc_IwcAPILzFLi9ASYU7ftO12ST7uqBUTteKwxqLWv4wqCiZzNiXEeCYQ4VhShwpLs0Y_dL-QEa26VhbQZ3TEnqvPQYs2s-jLkhVZFPbGNevgUNUxmUAArmpj5BRmBz8cfPY8yxCvIP9XwouAVUKYCM9mAHqKtOfTIWYmEarKVKnr6QQtrcLpt7yKtVkyJev67h_GY86qOfPkXDoQLhwfFlCumLbK2ThMRUNkDZ-ZWPtJA1y03TJZAfWGbhwYZ_RT120r_aMLiWUE1Rmz65osl6vjUl-Fg-FAqw


###

get 
http://localhost:9000/oauth2/authorize?response_type=code&client_id=messaging-client&scope=openid&code_challenge=QYPAZ5NU8yvtlQ9erXrUYR-T5AGCjCF47vN-KsaI2A8&code_challenge_method=S256&redirect_uri=http://127.0.0.1:3000/authorized

http://localhost:9000/oauth2/authorize?response_type=code&client_id=messaging-client&scope=openid&state=some-state&redirect_uri=http://127.0.0.1:3000/authorized

post 
http://localhost:9000/oauth2/token?client_id=messaging-client&redirect_uri=http://127.0.0.1:3000/authorized&grant_type=authorization_code&code=kTf0y6cukMT_b_fKUPoH-nM04XDrokzPy0-JFXxsrMFSj-f_KnBoqW9RZpqtAbaIAjIgLpxyp0avo65IWtAepjZ754yl7BJdoGbyeifXtLkzmjZjAjqt4fLnAvDO5bdf
Authorization: Basic btoa("messaging-client:secret")



const redirectUrl = `http://127.0.0.1:3000/authorized&grant_type=authorization_code&code=${code}&code_verifier=qPsH306-ZDDaOE8DFzVn05TkN3ZZoVmI_6x4LsVglQI`;
    return `http://localhost:8080/oauth2/token?client_id=client&redirect_uri=${redirectUrl}`;